login: &login
  adapter: mysql
  host: localhost
  username: root
  password:

development: &development
  database: kudoua_development
  <<: *login

test: &test
  database: kudoua_test
  <<: *login

production: &production
  adapter: mysql
  encoding:   utf8
  host: mysql0.locum.ru
  database: kudoua_kudo66
  pool: 5
  username: kudoua_kudo66
  password: xeddSLqv