login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: your_local_database
  <<: *login

test: &test
  database: your_test_database
  <<: *login

production: &production
  adapter: mysql2
  host: www.mysql0.locum.ru
  database: kudoua_kudo-ua18
  username: kudoua_kudo-ua18
  password: TsqP0caS