login: &login
  adapter: mysql
  host: localhost
  username: root
  password:

development: &development
  database: kudoua_development
  <<: *login

test: &test
  database: kudoua_test
  <<: *login

production: &production
  adapter: mysql
  host: mysql0.locum.ru
  database: kudoua_kudo-ua18
  username: kudoua_kudo-ua18
  password: TsqP0caS